name: bank_application
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3

  freezed: ^3.2.3
  freezed_annotation: 3.1.0

  google_fonts: ^6.2.1
  json_annotation: ^4.9.0

  pinput: ^6.0.0
  shared_preferences: ^2.2.2

dev_dependencies:
  build_runner: ^2.4.6
  json_serializable: ^6.8.0
  flutter_gen_runner: ^5.3.1
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

  riverpod_generator: ^3.0.3

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/data/investment_companies_list.json
    - assets/images/
